export function okfPrompt(): string {
  return [
    "The OKF library plugin compiles documents (PDF and more) into a local OKF markdown library under the current session workspace.",
    "Default library folder is OKF/ inside that workspace unless okf_set_paths or OKF_DIR overrides it.",
    "Cite only concept ids that tools returned (papers/…, claims/…). Never invent Paper ids or DOIs.",
    "",
    "Layout inside OKF/:",
    "- Concept pages: papers/, topics/, methods/, entities/, claims/, notes/, questions/, surveys/, extracts/",
    "- Sources (local only, not packed): sources/pdfs/ (PDFs) and sources/docs/ (docx/pptx/xlsx/epub/rtf/csv/md/…)",
    "- Manuscripts (not a concept prefix, not packed): manuscripts/",
    "Inspect resolved absolute paths for THIS session with okf_paths. Never invent another machine's absolute path.",
    "Move a library between workspaces with okf_pack then okf_merge (folder or .zip). Users can also export and merge themselves.",
    "Durable truth is files in OKF/ (and job_output for ingest/compile). Job-internal model calls are not this conversation's assistant messages.",
    "",
    "Agent routing — never load a paper body unless you need one specific page. A library may have ~1000 papers; full-text dumps stall the harness.",
    "OKF is already a typed graph: Topic/Method/Entity/Dataset/Gene/Pathway are hubs, Claim is the citation atom, Paper is a digest with links. Use those instead of chunking PDFs.",
    "0. Usage / 使用说明 / 怎么用 / okf 是否有使用说明 / example prompts: call okf_help and answer from that payload. Do not invent a different workflow.",
    "1. Census / 'what's in this library' / commonalities at scale: okf_stats (counts, years, top hubs). Then okf_compare with query= or a short papers list — never okf_compare on the whole 1000-paper set.",
    "2. 'What does the literature say' / evidence: okf_evidence (top Claim pages). Cite claims/ ids. Follow with okf_get on one claim or paper only if the excerpt is not enough.",
    "3. Keyword lookup: okf_search with optional type, from/to (published year or date), and tags. Claims in a year range: okf_evidence with from/to (filters by the linked paper date).",
    "4. Topic × year gaps: okf_coverage.",
    "5. Neighborhood snapshot: okf_graph (claims off unless asked). Who cites this concept / which papers used this dataset/gene: okf_backlinks (type=Paper). Direct neighbors: okf_neighbors. Multi-hop: okf_graph with id + depth. Health audit / 检查文库 / 文库是否完整 / 有没有断链 / 孤立节点 / 为什么某篇没有连线: okf_check. Unquoted claims are dropped automatically, not a human queue. Near-duplicate hubs in the review inbox: confirm with the user then okf_canonicalize from→to. Missing published date or DOI also appears under 需处理.",
    "6. One concept page: okf_get. Default body is capped. At most one or two per turn; full=true only for that one page. Do not okf_get extracts/*.md — search promotes extract hits to papers/.",
    "7. Ingest: okf_ingest with document paths or directories (PDF/docx/pptx/xlsx/epub/rtf/csv/md/…) — relative to OKF/sources/ (sources/pdfs for PDFs) or pdfDir, or absolute on THIS machine. run_in_background defaults true. Read progress with job_output. PDFs: text layer via anydoc (Rust); node rasters planned vision pages and sends them to the harness multimodal model (2 pages per request, retries timeouts, resumes remaining pages). Compile map-reduces the full extract in ~12k-character segments so methods/results later in the PDF are not dropped. Non-PDF formats convert straight to Markdown (no vision). Vision policy: vision=auto (default) transcribes every planned page with no pause (scans: all pages; born-digital: figure + thin-text pages); vision=all sends every PDF page; figures / skip / pages:N,N,N remain; skipVision=true is the legacy alias for skip. Optional visionMaxPages pauses auto above that count. Status needs_vision with error Request timed out: retry okf_ingest on those documents.",
    "8. Compile existing extracts: omit paper to compile every extract. paper= may be papers/id, extracts/*.md, or a source filename (PDF or other).",
    "9. Survey: draft markdown with [label](/papers/….md) or [label](/claims/….md) links, okf_cite_check, then okf_save_survey. Optional okf_compile_survey is a background job.",
    "10. Export: okf_bib / okf_export write a manuscript + .bib under OKF/manuscripts/ by default (never invent bibliography entries).",
    "",
    "Do not set a plugin API key or pick an OKF library model. The harness owns provider and model selection.",
  ].join("\n");
}
